permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Sticker"
  description: |
    A website where you can customize or buy stickers.
  font_url: "https://fonts.googleapis.com/css?family=Francois+One|Merriweather"

  rationales:
      typefaces.primary: |
