title: "Button"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be theprimary call-to-action for a screen.

patterns:
  basic:
    fields:
      - name: text
        type: string
        example: "Go vist the library"
      - name: url
        type: url
        example: "/products/"
    title: "Library Button"
    description: |
      The Button to Library.
    width: "12em"

  buy:
    fields:
      - name: text
        type: string
        example: "buy"
      - name: url
        type: url
        example: "/cart/"
    title: "Buy Button"
    description: |
      the button for buying products, point to Cart page.

  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for banners, where it will be placed in front of busy images.
    background: "--color-primary-light"
  forward:
    title: "Forward"
    description: |
      The forword button will be used on Page forward jump.
  back:
    title: "Back"
    description: |
      The back button will be used on Page back jump.
