title: "Banner"
description: |
  Cards are a convenient means of displaying content composed of different types of objects. Theyâ€™re also well-suited for presenting similar objects whose size or supported actions can vary considerably, like photos with captions of variable length.

patterns:
    banner_1:
      fields:
        - name: heading
          type: string
          example: "Welcome to Sticker!"
