title: "Form"
description: |
  Forms are the standard way to receive user inputted data. The transitions and smoothness of these elements are very important because of the inherent user interaction associated with forms.

patterns:
  type_1_form_part_1:
    title: "Type 1 from part 1"
    description: |
      The Navigation Bar will be used on every pages.
