title: "Form"
description: |
  Forms are the standard way to receive user inputted data. The transitions and smoothness of these elements are very important because of the inherent user interaction associated with forms.

patterns:
  type_1_form_part_1:
    title: "Checkout Form Part.1"
    description: |
      This is a chectout form.

  type_1_form_part_2:
    title: "Checkout Form Part.2"
    description: |
      This is another chectout form.
